default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: shop_api_development

test:
  <<: *default
  database: shop_api_test

production:
  primary:
    <<: *default
  cable:
    <<: *default
