# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  # (если у тебя локально не через DATABASE_URL, можно оставить твои dev-поля)

test:
  <<: *default

production:
  primary:
    <<: *default
  cable:
    <<: *default
