# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "kirill") %>
  password: <%= ENV.fetch("DB_PASSWORD", "12345") %>
  database: <%= ENV.fetch("DB_NAME", "shop_api_development") %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "kirill") %>
  password: <%= ENV.fetch("DB_PASSWORD", "12345") %>
  database: <%= ENV.fetch("DB_NAME_TEST", "shop_api_test") %>

production:
  <<: *default
  # в проде используй только DATABASE_URL (задашь на хостинге)
